config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root 'posts#index'
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def self.user_comments(post_id)
    joins(:user).where(post_id: post_id).select(:id,:body, :email,:created_at,:post_id,:user_id)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates_presence_of :body

  has_many :comments, dependent: :destroy
  belongs_to :user
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: ->(attrs){ attrs['name'].blank? }
  scope :ordenados, ->() { order(created_at: :desc) }
  
  def self.p_user(u_id)
    joins(:user).select(:id,:email,:created_at,:title ,:body,:user_id).find_by(id: u_id)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  helper_method :comment
  before_action :set_post, only: [:create, :destroy]

  def create
    #@comment = @post.comments.build(comment_params.merge(user_id: current_user.id))
    redirect_to post_path(@post) if comment.save
  end

  def destroy
    redirect_to post_path(@post) if comment.destroy
  end

  private
  
  def comment_params
    params.permit(:post_id, comment: [:body])
  end
  
  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment_post
    @comment = @post.comments.find_by(id: params[:id])
  end

  def comment
    @comment ||=
    if action_name.eql?("create")
      current_user.comments.build(body: params[:comment][:body], post_id: params[:post_id])
    else
      set_comment_post rescue nil
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  helper_method :post
  helper_method :comment
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:edit, :destroy, :update]
  
  def index; end

  def new; end

  def show; end
  
  def edit; end

  def create
    if post.save
      redirect_to posts_path
    else 
      render 'new'
    end
  end

  def update
    if post.update(post_params)
      redirect_to post
    else 
      render 'edit'
    end
  end

  def destroy
    redirect_to posts_path if post.destroy
  end

  private
  
  def post_params
    params.require(:post).permit(:title, :body, tags_attributes: [:_destroy, :id, :name])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post
    @post ||=
    case action_name
    when "index"
     Post.ordenados
    when "new"
      Post.new
    when "new","create"
      current_user.posts.build(post_params)      
    when "show"
      Post.p_user(params[:id])
    else
      set_post rescue nil
    end
  end

  def comment
    @comment ||= 
    Comment.user_comments(params[:id]) if action_name.eql? "show"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
    <div class="comment_content">
      <p class="comment_body"><%= comment.email %></p>
      <p class="comment_body"><%= comment.body %></p>
      <p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago</p>
      <% if user_signed_in? and (current_user.id.eql? (post.user_id) or current_user.id.eql? (comment.user_id)) %>
      <p><%= link_to 'Destroy Comment', [comment.post, comment],
               method: :delete, class: 'button', style: 'float: left;background-color: red;color: white;',
               data: { confirm: 'Are you sure?' } %></p>
      <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([post, post.comments.build]) do |f| %>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <br>
    <p>
      <%= f.submit %>
    </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tumblr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<ul>
			<li class="category"><%= link_to "Tumblr", root_path %></li>
			<li><%= link_to "Posts", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>
		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
		<% end %>	

	</div>

	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>Post Feed</p>
			<% elsif current_page?(about_path) %>
				<p>My Site</p>
			<% else %>
				<%= link_to "Back to Post Feed", root_path %>
			<% end %>
			<% if user_signed_in? %>
				<div class="buttons">
					<button class="button"><%= link_to "Make Post", new_post_path %></button>
					<button class="button"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></button>
				</div>
			<% end %>


		</div>	
		
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>

	</div>



</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpeg" %>
	</div>
	
	<div id="content">
		<h1>It's Mr. Stick Figure </h1>
		<p>Single-origin coffee four loko post-ironic gluten-free. Cardigan hella banjo polaroid artisan, kitsch trust fund cray. Austin asymmetrical gentrify, marfa put a bird on it gastropub intelligentsia migas cray. Put a bird on it tattooed synth, gentrify semiotics asymmetrical chambray yr distillery beard brooklyn keytar. Before they sold out pinterest occupy, VHS bitters kitsch twee. PBR&B leggings master cleanse, bicycle rights YOLO messenger bag taxidermy ramps. Locavore tote bag whatever meditation mustache.</p>

	</div>

</div>

app/views/posts/_form.html.erb
<% post.tags.build %>
<%= form_for post do |f| %>
    <% if post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(post.errors.count, "error") %> stopeed this post from saving</h2>
        <ul>
          <% post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
  
    <h2>Tags</h2>
    <%= render partial: 'tags/form', locals: {:form => f } %>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% post.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to  post.title, post  %></h2>
    <p class="body"><%= truncate(post.body, length:100) %></p>
    <p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Create post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(post.created_at) %>
    <% if user_signed_in? and current_user.id.eql? (post.user_id) %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }  %>
    <% end %>
  </p>

  <p class="body">
    <%= post.body %>
    <br>
    By <%= post.email %>
  </p>
  <p>
    <b>Tags:</b>
      <%= post.tags.map { |t| t.name }.join(", ") %>
  </p>
  <div id="comments">
    <h2><%= post.comments.count %> Comments</h2>
    <%= render comment %>
    <h3> Join Discussion: </h3>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>